# Generated by Django 2.2.16 on 2022-12-15 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Может состоять из символов латиницы и кириллицы, а также содержать цифры', max_length=200, verbose_name='Название группы')),
                ('slug', models.SlugField(help_text='Может состоять только из символов латиницы в нижнем регистре, а также цифр', unique=True, verbose_name='Уникальная строка идентификатор группы')),
                ('description', models.TextField(help_text='Краткое описание группы, чтобы можно было понять какие записи размещают в этой группе', verbose_name='Описание группы')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Напиши о чем угодно, но не обижай других пользователей', verbose_name='Текст записи')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Указывает на время создания записи. Автоматически проставляется текущее время, если не указана другая дата', verbose_name='Дата создания записи')),
                ('image', models.ImageField(blank=True, help_text='Картинка будет размещена вверху поста.', upload_to='posts/', verbose_name='Картинка')),
                ('author', models.ForeignKey(help_text='Пользователь, создавший запись. Только он имеет правана её редактирование', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
                ('group', models.ForeignKey(blank=True, help_text='Группа, в которой будет размещена запись.Необязательное поле.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.Group', verbose_name='Группа')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(help_text='Указывает на автора, на которого подписался пользователь.', on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('user', models.ForeignKey(help_text='Указывает на пользователя, который подписывается', on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL, verbose_name='Тот, кто подписывается')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, help_text='Напиши о чем угодно, но не обижай других пользователей', verbose_name='Текст комментария')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Указывает на время создания комментария. Автоматически проставляется текущее время, если не указана другая дата', verbose_name='Дата создания комментария')),
                ('author', models.ForeignKey(help_text='Указывает на автора, который создал комментарий.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('post', models.ForeignKey(help_text='Указывает на пост, к которому создан комментарий.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.Post', verbose_name='Пост')),
            ],
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_follow'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('author')), name='check_follow'),
        ),
    ]
